version: "3.5"

volumes:
  redis-data:
    driver: local
  pg-data:
services:
  redis:
    container_name: employee-goal-rates-api-redis
    restart: always
    image: redis
    expose:
      - 6379
    volumes:
      - redis-data:/data
    networks:
      - employee-goal-rates-network
  php-fpm:
    container_name: employee-goal-rates-api-php
    build:
      context: .
      dockerfile: ./dockerdata/Dockerfile
      network: host
    image: employee-goal-rates-api
    working_dir: /var/www/html
    depends_on:
      - redis
    volumes:
      - ./:/var/www/html
      - ./dockerdata/php_override.ini:/usr/local/etc/php/conf.d/override.ini
    expose:
      - 9000
    command: [ "/bin/bash", "/var/www/html/dockerdata/run.sh" ]
    networks:
      - employee-goal-rates-network
  nginx:
    container_name: employee-goal-rates-api-nginx
    image: nginx:alpine
    privileged: true
    volumes:
      - ./:/var/www/html
      - ./dockerdata/nginx/config/nginx.conf:/etc/nginx/nginx.conf
      - ./dockerdata/nginx/config/sites-enabled:/etc/nginx/sites-enabled
    ports:
      - 8080:80
    command: [ "/bin/sh","/var/www/html/dockerdata/run.sh" ] #odpalamy skrypt wyzej opisany
    environment:
      CONTAINER_ROLE: nginx
    networks:
      - employee-goal-rates-network
  db:
    container_name: employee-goal-rates-api-postgres
    image: postgres:14.3
    restart: always
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - '29999:5432'
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - employee-goal-rates-network
networks:
  employee-goal-rates-network:
    name: employee-goal-rates-network
    driver: bridge



